version: '3'
services:
    web:
      build: ./panel
      network_mode: "host"
      environment:
        CLIENT_ID: ${CLIENT_ID}
        CLIENT_SECRET: ${CLIENT_SECRET}
      depends_on:
        db:
          condition: service_healthy
    bot:
      build: ./bot
      network_mode: "host"
      environment:
        BOT_TOKEN: ${BOT_TOKEN}
      depends_on:
        db:
          condition: service_healthy
    db:
      build: ./db
      ports:
        - "5432:5432"
      environment: 
        POSTGRES_PASSWORD: password
        POSTGRES_DB: bot_panel
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
